name: Build Release v2.0 Images

on:
  push:
    branches:
      - release-v2.0
  workflow_dispatch: # 允许手动触发

env:
  BUILD_VERSION: v2.0.5

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cross Build
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/go/src/github.com/containerd/nerdctl \
            -w /go/src/github.com/containerd/nerdctl \
            -e BUILD_VERSION=${{ env.BUILD_VERSION }} \
            ghcr.io/${{ github.repository_owner }}/golang:1.23 \
            bash -c "rm -rf vendor && go mod vendor && bash .beagle/build.sh"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/nerdctl:${{ env.BUILD_VERSION }}-amd64
          build-args: |
            BASE=alpine:3
            VERSION=${{ env.BUILD_VERSION }}
            TARGETOS=linux
            TARGETARCH=amd64
          provenance: false
          sbom: false

      - name: Build and push images for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/nerdctl:${{ env.BUILD_VERSION }}-arm64
          build-args: |
            BASE=alpine:3
            VERSION=${{ env.BUILD_VERSION }}
            TARGETOS=linux
            TARGETARCH=arm64
          provenance: false
          sbom: false

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/nerdctl:${{ env.BUILD_VERSION }} \
            ghcr.io/${{ github.repository_owner }}/nerdctl:${{ env.BUILD_VERSION }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/nerdctl:${{ env.BUILD_VERSION }}-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/nerdctl:${{ env.BUILD_VERSION }}
