name: lint

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

env:
  GO_VERSION: 1.23.x

jobs:
  go:
    timeout-minutes: 5
    name: "go | ${{ matrix.goos }} | ${{ matrix.canary }}"
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            goos: linux
          - os: ubuntu-24.04
            goos: freebsd
          # FIXME: this is currently failing in a non-sensical way, so, running on linux instead...
          # - os: windows-2022
          - os: ubuntu-24.04
            goos: windows
          - os: ubuntu-24.04
            goos: linux
            # This allows the canary script to select any upcoming golang alpha/beta/RC
            canary: go-canary
    env:
      GOOS: "${{ matrix.goos }}"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 1
      - name: Set GO env
        run: |
          # If canary is specified, get the latest available golang pre-release instead of the major version
          if [ "$canary" != "" ]; then
            . ./hack/build-integration-canary.sh
            canary::golang::latest
          fi
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a  # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84  # v6.5.2
        with:
          args: --verbose
  other:
    timeout-minutes: 5
    name: yaml | shell | imports order
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a  # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: yaml
        run: make lint-yaml
      - name: shell
        run: make lint-shell
      - name: go imports ordering
        run: |
          go install -v github.com/incu6us/goimports-reviser/v3@latest
          make lint-imports
