name: project

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  project:
    name: checks
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          path: src/github.com/containerd/nerdctl
          fetch-depth: 100
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34  # v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: src/github.com/containerd/nerdctl
      - uses: containerd/project-checks@434a07157608eeaa1d5c8d4dd506154204cd9401  # v1.1.0
        with:
          working-directory: src/github.com/containerd/nerdctl
          repo-access-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./hack/verify-no-patent.sh
        working-directory: src/github.com/containerd/nerdctl
      - run: ./hack/verify-pkg-isolation.sh
        working-directory: src/github.com/containerd/nerdctl
